apiVersion: v1
kind: ConfigMap
metadata:
  name: card-service-config
data:
  DB_URL: jdbc:postgresql://postgres:5432/card_platform
  DB_USERNAME: card_app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
  labels:
    app.kubernetes.io/name: card-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: card-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: card-service
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      containers:
        - name: card-service
          image: card-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: card-service-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: card-service-secrets
                  key: db-password
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /q/health/started
              port: http
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  selector:
    app.kubernetes.io/name: card-service
  ports:
    - name: http
      port: 80
      targetPort: http
